Remove unused lines fs/exec.c:531: undefined reference to `flush_kernel_dcache_page' fs/exec.c:549: undefined reference to `flush_kernel_dcache_page'
lib/scatterlist.c:423: undefined reference to `flush_kernel_dcache_page'

Signed-off-by: Jean Francis Dominique S. Mabalot <jfdsmabalot@redhat.com>